### ISSUE TITLE
Zuul gate is executing for this repo.

### ISSUE THREAD

**Issue by harshad16** [thoth-station/ansible-role-argo-workflows#12]
**Describe the bug**
The pull request merge gate by zuul is not executing for the PR's in the repo.

**To Reproduce**
1. Raise a PR
2. Get it approved by write access enabled user.
3.  Check if zuul -gate merges it.  

**Expected behavior**
PR to get automatically merged once PR is approved.
 
**Additional context**
Try `regate` as well to test.

**Comment by goern** [comment]
I reconfigured the team 'Devs' to have write access to this repo. please monitor...
